export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_RECEIVED = 'PRODUCT_LIST_RECEIVED';
export const FILTERED_PRODUCT_LIST_RECEIVED = 'FILTERED_PRODUCT_LIST_RECEIVED';
export const SEARCH_PRODUCT_LIST_RECEIVED = 'SEARCH_PRODUCT_LIST_RECEIVED';
export const FILTERED_PRODUCT_LIST_DELETED = 'FILTERED_PRODUCT_LIST_DELETED';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_ADD = 'PRODUCT_LIST_ADD';
export const PRODUCT_LIST_SET_PAGE = 'PRODUCT_LIST_SET_PAGE';
export const PRODUCT_LIST_SET_CATEGORY_PAGE = 'PRODUCT_LIST_SET_CATEGORY_PAGE';

export const RECEIVED_ALL_PRODUCTS = 'RECEIVED_ALL_PRODUCTS';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const PRODUCT_UNLOAD = 'PRODUCT_UNLOAD';

export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_RECEIVED = 'CATEGORY_LIST_RECEIVED';
export const CATEGORY_LIST_ERROR = 'CATEGORY_LIST_ERROR';
export const CATEGORY_LIST_ADD = 'CATEGORY_LIST_ADD';

export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_RECEIVED = 'CART_LIST_RECEIVED';
export const CART_LIST_RECEIVED_ALL = 'CART_LIST_RECEIVED_ALL';
export const CART_LIST_ERROR = 'CART_LIST_ERROR';
export const CART_LIST_UNLOAD = 'CART_LIST_UNLOAD';

export const CART_PRODUCT_ADDED = 'CART_PRODUCT_ADDED';
export const CART_PRODUCT_ADDED_ERROR = 'CART_PRODUCT_ADDED_ERROR';
export const CART_PRODUCT_DELETED = 'CART_PRODUCT_DELETED';
export const CART_PRODUCT_UPDATED = 'CART_PRODUCT_UPDATED';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_SET_ID = 'USER_SET_ID';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED';
export const USER_PASSWORD_UPDATED = 'USER_PASSWORD_UPDATED';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';

export const MODIFY_SESSION = 'MODIFY_SESSION';
export const ADD_PRODUCT_TO_SESSION = 'ADD_PRODUCT_TO_SESSION';
export const DELETE_PRODUCT_FROM_SESSION = 'DELETE_PRODUCT_FROM_SESSION';
export const DELETE_CART_FROM_STATE = 'DELETE_CART_FROM_STATE';

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_RECEIVED = "PAYMENT_RECEIVED";
export const PAYMENT_ERROR = "PAYMENT_ERROR";
export const PAYMENT_UNLOAD = "PAYMENT_UNLOAD";

export const COUPON_RECEIVED = "COUPON_RECEIVED";
export const COUPON_ERROR = "COUPON_ERROR";

export const COMBO_DEALS_LIST_RECEIVED = "COMBO_DEALS_LIST_RECEIVED";

export const FEATURED_PRODUCTS_LIST_RECEIVED = "FEATURED_PRODUCTS_LIST_RECEIVED";

export const DISCOUNT_PRODUCTS_LIST_RECEIVED = "DISCOUNT_PRODUCTS_LIST_RECEIVED";

